### ISSUE TITLE
main.py里面代码的小问题

### ISSUE THREAD

**Issue by czhxiaohuihui** [Nrgeup/controllable-text-attribute-transfer#2]
你好，请问main.py第157行的dis_optimizer.step()是多余的吗？还是有什么别的用途？？？

**Comment by LiuJoffrey** [comment]
您好，請問在 paper 中所提到的 model 架構上有使用到 GRU 來 encode sequence information，但是從 model.py 中並未找到此 layer，想請問是為什麼呢？？

**Comment by Nrgeup** [comment]
是多余的。抱歉，我会再清理一下。
