### ISSUE TITLE
Should use GRU with self-attention layer to encode the sentence?

### ISSUE THREAD

**Issue by LiuJoffrey** [Nrgeup/controllable-text-attribute-transfer#3]
您好，請問在 paper 中所提到的 model 架構上有使用到 GRU 來 encode sequence information，但是從 model.py 中並未找到此 layer，想請問是為什麼呢？？

**Comment by Nrgeup** [comment]
加上了GRU层后训练会变慢好几倍，这里先放出一个简单版本的，后面会清理一下再放出代码和checkpoint。
