### ISSUE TITLE
如何訓練出paper 所顯示的數據？

### ISSUE THREAD

**Issue by LiuJoffrey** [Nrgeup/controllable-text-attribute-transfer#4]
您好，我目前在 reproduce 此 project ，希望能夠得出與paper 所實驗的結果。因為此份 code 所提供的 model在 encoder 後的部分並沒有加上 GRU  layer，故我如 paper 所述將encoder 的輸出加上 positional embedding （在此我使用 model.py 的positionlayer）並通過 GRU (bidirectional with 128 hidden size)後在接著 sum 以及 sigmoid。然而訓練200個 epoch 後仍然沒有取得相同的實驗結果。想請問 model 這樣的設計是否與 paper 所述相同，以及除了 model 尚未更新外，還有哪些地方需要更新才能與 paper 實驗相同（training process, loss function 等），非常謝謝您的幫忙，拜託了

**Comment by Nrgeup** [comment]
您好，加上GRU layer的model文件是model2.py, 我已经把三个数据集的代码和checkpoint(这里是没有GRU [layer的，因为加了GRU效果提升了一点，但是非常耗时，后期我整理再放上去)都放上去了。另外，模型的Outputs在'outputs/*'文件下。

**Comment by linzehui** [comment]
@LiuJoffrey 请问最后你复现成功了吗？
