### ISSUE TITLE
I cannot find a GRU in your implementation?

### ISSUE THREAD

**Issue by Akella17** [Nrgeup/controllable-text-attribute-transfer#7]
@Nrgeup Your paper mentions the use of a GRU to more effectively incorporate the word-level sequential context. However, I don't see any GRU blocks in your model. Is there any reason why this is the case?

**Comment by Nrgeup** [comment]
You can find the implementation in [model2.py](https://github.com/Nrgeup/controllable-text-attribute-transfer/blob/74cf2633080870a376a769aea9ce731813126b6a/method/mymodel-yelp/model2.py).

**Comment by Akella17** [comment]
I somehow seemed to have overlooked that. Thanks :+1:
